version: "3"

services:
  app:
    build: 
      context: .
    ports:
      - "8888:8888"
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8888
    volumes:
      - ./app:/app/